import { NextRequest, NextResponse } from "next/server";
import { prisma } from "@/lib/db";
import { analyzeJobDescription } from "@/lib/claude";
import { scrapeJobUrl } from "@/lib/parsers/web";
import { normalizeJobUrl } from "@/lib/utils/normalize-url";
import { enqueueJob } from "@/lib/job-queue";
import { createLogger, createTaskLogger } from "@/lib/logger";
import { withLogging } from "@/lib/api-handler";
import { getAppSettings } from "@/lib/app-settings";

const log = createLogger("jobs");

function buildJobReviewUrl(jobId: string): string {
  return `/jobs?jobId=${encodeURIComponent(jobId)}`;
}

export const GET = withLogging(async (request: NextRequest) => {
  const page = Math.max(1, parseInt(request.nextUrl.searchParams.get("page") || "1", 10));
  const pageSize = Math.min(50, Math.max(1, parseInt(request.nextUrl.searchParams.get("pageSize") || "10", 10)));
  const hasResumes = request.nextUrl.searchParams.get("hasResumes") === "true";
  const excludeApplied = request.nextUrl.searchParams.get("excludeApplied") === "true";
  const excludeNoSponsorship = request.nextUrl.searchParams.get("excludeNoSponsorship") === "true";
  const skip = (page - 1) * pageSize;

  const where: Record<string, unknown> = {};
  if (hasResumes) where.resumes = { some: {} };
  if (excludeApplied) where.applied = false;
  if (excludeNoSponsorship) where.sponsorship = { not: "unavailable" };

  const [jobs, total] = await Promise.all([
    prisma.job.findMany({
      where,
      orderBy: { createdAt: "desc" },
      include: {
        resumes: {
          orderBy: { createdAt: "desc" },
          select: { id: true, format: true, createdAt: true },
        },
        profileVersions: {
          orderBy: { createdAt: "desc" },
          select: {
            id: true,
            score: true,
            scoreVersion: true,
            delta: true,
            createdAt: true,
            resumes: { orderBy: { createdAt: "desc" }, select: { id: true, format: true, createdAt: true } },
          },
        },
      },
      skip,
      take: pageSize,
    }),
    prisma.job.count({ where }),
  ]);

  return NextResponse.json({
    jobs,
    total,
    page,
    pageSize,
    totalPages: Math.ceil(total / pageSize),
  });
});

export const DELETE = withLogging(async (request: NextRequest) => {
  const { ids } = await request.json();

  if (!Array.isArray(ids) || ids.length === 0 || ids.length > 100) {
    return NextResponse.json(
      { error: "Provide an array of 1-100 job IDs to delete" },
      { status: 400 }
    );
  }

  // Validate all IDs are strings
  if (!ids.every((id: unknown) => typeof id === "string")) {
    return NextResponse.json(
      { error: "All IDs must be strings" },
      { status: 400 }
    );
  }

  const result = await prisma.job.deleteMany({
    where: { id: { in: ids } },
  });

  log.info("jobs_deleted", { count: result.count, requestedCount: ids.length });

  return NextResponse.json({ deleted: result.count });
});

export const PATCH = withLogging(async (request: NextRequest) => {
  const { jobId, aiModel } = await request.json();

  if (!jobId || typeof jobId !== "string") {
    return NextResponse.json({ error: "jobId is required" }, { status: 400 });
  }

  const validModels = ["sonnet", "opus"];
  if (!aiModel || !validModels.includes(aiModel)) {
    return NextResponse.json(
      { error: `aiModel must be one of: ${validModels.join(", ")}` },
      { status: 400 }
    );
  }

  const job = await prisma.job.findUnique({ where: { id: jobId } });
  if (!job) {
    return NextResponse.json({ error: "Job not found" }, { status: 404 });
  }

  // Delete stale downstream data generated by the old model
  await Promise.all([
    prisma.profileVersion.deleteMany({ where: { jobId } }),
    prisma.resume.deleteMany({ where: { jobId } }),
  ]);

  // Reset analysis fields and update model
  const updated = await prisma.job.update({
    where: { id: jobId },
    data: {
      aiModel,
      title: "Re-analyzing...",
      skills: null,
      requirements: null,
      atsKeywords: null,
      seniority: null,
      roleArchetype: null,
      terminologyMap: null,
      matchResult: null,
      matchedAt: null,
    },
  });

  // Fire async re-analysis + pipeline (same pattern as POST)
  const taskLog = createTaskLogger("job-reanalysis", jobId);
  analyzeJobDescription(job.description, { model: aiModel })
    .then(async (analysis) => {
      await prisma.job.update({
        where: { id: jobId },
        data: {
          title: (analysis.title as string) || "Untitled Position",
          company: (analysis.company as string) || "Unknown Company",
          skills: JSON.stringify(analysis.skills || []),
          requirements: JSON.stringify(analysis.requirements || []),
          atsKeywords: JSON.stringify(analysis.atsKeywords || {}),
          seniority: analysis.seniority || null,
          roleArchetype: analysis.roleArchetype || null,
          sponsorship: (analysis.sponsorship as string) || "unspecified",
          terminologyMap: JSON.stringify(analysis.terminologyMap || []),
        },
      });
      taskLog.complete({ model: aiModel, title: analysis.title as string });
      enqueueJob(
        "auto-pipeline",
        { jobId },
        { entityId: jobId, entityType: "job", maxAttempts: 2 }
      ).catch((enqueueErr) => {
        log.error("auto_pipeline_enqueue_failed", {
          jobId,
          error: enqueueErr instanceof Error ? enqueueErr : new Error(String(enqueueErr)),
        });
      });
    })
    .catch((err) => {
      taskLog.fail(err);
      prisma.job
        .update({
          where: { id: jobId },
          data: { title: "Analysis Failed — Click to Retry" },
        })
        .catch((dbErr) => log.error("reanalysis_fallback_update_failed", { jobId, error: dbErr instanceof Error ? dbErr : new Error(String(dbErr)) }));
    });

  return NextResponse.json({ ...updated, analysisStatus: "pending" });
});

export const POST = withLogging(async (request: NextRequest) => {
  const {
    url,
    description,
    aiModel,
    source,
    titleHint,
    companyHint,
    locationHint,
  } = await request.json();

  if (!url && !description) {
    return NextResponse.json(
      { error: "Provide either a URL or a job description" },
      { status: 400 }
    );
  }

  // Duplicate check by URL — match against both url and canonicalUrl on existing jobs
  // so the extension path catches jobs previously imported via the batch route
  // (which resolves aggregator → employer ATS into canonicalUrl).
  const normalizedIncoming = url ? normalizeJobUrl(url) : "";
  if (normalizedIncoming) {
    const existing = await prisma.job.findMany({
      where: { OR: [{ url: { not: null } }, { canonicalUrl: { not: null } }] },
      select: { id: true, url: true, canonicalUrl: true, title: true, company: true },
    });
    const dup = existing.find((j) => {
      if (j.url && normalizeJobUrl(j.url) === normalizedIncoming) return true;
      if (j.canonicalUrl && normalizeJobUrl(j.canonicalUrl) === normalizedIncoming) return true;
      return false;
    });
    if (dup) {
      return NextResponse.json(
        {
          error: `This job has already been added (${dup.title} at ${dup.company})`,
          duplicate: true,
          duplicateKind: "job",
          existingJobId: dup.id,
          title: dup.title,
          company: dup.company,
          reviewUrl: buildJobReviewUrl(dup.id),
        },
        { status: 409 }
      );
    }
  }

  // Duplicate check by description prefix (for pasted text)
  if (description && !url) {
    const prefix = description.trim().slice(0, 200);
    const allJobs = await prisma.job.findMany({
      select: { id: true, description: true, title: true, company: true },
    });
    const dup = allJobs.find((j) => j.description.trim().slice(0, 200) === prefix);
    if (dup) {
      return NextResponse.json(
        {
          error: `This job description already exists (${dup.title} at ${dup.company})`,
          duplicate: true,
          duplicateKind: "job",
          existingJobId: dup.id,
          title: dup.title,
          company: dup.company,
          reviewUrl: buildJobReviewUrl(dup.id),
        },
        { status: 409 }
      );
    }
  }

  // Get job description text (this is I/O but necessary before we can save)
  let jobText = description;
  if (url && !description) {
    jobText = await scrapeJobUrl(url);
  }

  if (!jobText || jobText.trim().length < 50) {
    return NextResponse.json(
      {
        error:
          "Could not extract enough text from that URL. Try pasting the job description directly instead.",
      },
      { status: 400 }
    );
  }

  const settings = await getAppSettings();

  // Save the job immediately with the raw text — user sees it appear right away.
  // Re-check URL dedupe inside a transaction to close the race between the initial
  // check above and the create (the scrape call is a slow async I/O in between).
  const createResult = await prisma.$transaction(async (tx) => {
    if (normalizedIncoming) {
      const existing = await tx.job.findMany({
        where: { OR: [{ url: { not: null } }, { canonicalUrl: { not: null } }] },
        select: { id: true, url: true, canonicalUrl: true, title: true, company: true },
      });
      const dup = existing.find((j) => {
        if (j.url && normalizeJobUrl(j.url) === normalizedIncoming) return true;
        if (j.canonicalUrl && normalizeJobUrl(j.canonicalUrl) === normalizedIncoming) return true;
        return false;
      });
      if (dup) return { duplicate: dup };
    }
    const created = await tx.job.create({
      data: {
        title: "Analyzing...",
        company:
          (typeof companyHint === "string" && companyHint.trim()) ||
          (url
            ? new URL(url).hostname.replace("www.", "").split(".")[0]
            : "Analyzing..."),
        url: url || null,
        description:
          typeof locationHint === "string" && locationHint.trim() && !jobText.includes(locationHint)
            ? `Location: ${locationHint.trim()}\n\n${jobText}`
            : jobText,
        skills: null,
        requirements: null,
        atsKeywords: null,
        seniority: null,
        roleArchetype: null,
        sponsorship: "unspecified",
        aiModel: aiModel || settings.defaultAiModel,
        source: source || null,
      },
    });
    return { created };
  });

  if (createResult.duplicate) {
    const dup = createResult.duplicate;
    return NextResponse.json(
      {
        error: `This job has already been added (${dup.title} at ${dup.company})`,
        duplicate: true,
        duplicateKind: "job",
        existingJobId: dup.id,
        title: dup.title,
        company: dup.company,
        reviewUrl: buildJobReviewUrl(dup.id),
      },
      { status: 409 }
    );
  }

  const job = createResult.created!;

  log.info("job_created", { jobId: job.id, hasUrl: !!url, descriptionLength: jobText.length });

  // Fire Claude analysis asynchronously — don't block the response
  const taskLog = createTaskLogger("job-analysis", job.id);
  analyzeJobDescription(jobText, { model: job.aiModel })
    .then(async (analysis) => {
      await prisma.job.update({
        where: { id: job.id },
        data: {
          title:
            (analysis.title as string) ||
            (typeof titleHint === "string" && titleHint.trim()) ||
            "Untitled Position",
          company:
            (analysis.company as string) ||
            (typeof companyHint === "string" && companyHint.trim()) ||
            job.company,
          skills: JSON.stringify(analysis.skills || []),
          requirements: JSON.stringify(analysis.requirements || []),
          atsKeywords: JSON.stringify(analysis.atsKeywords || {}),
          seniority: analysis.seniority || null,
          roleArchetype: analysis.roleArchetype || null,
          sponsorship: (analysis.sponsorship as string) || "unspecified",
          terminologyMap: JSON.stringify(analysis.terminologyMap || []),
        },
      });
      taskLog.complete({ title: analysis.title as string });
      // Enqueue the v2 resume quality pipeline on the BackgroundJob worker so it
      // survives Next.js restarts and gets retry semantics. Pipeline progress is
      // tracked on Job.pipelineStatus / pipelineStage.
      enqueueJob(
        "auto-pipeline",
        { jobId: job.id },
        { entityId: job.id, entityType: "job", maxAttempts: 2 }
      ).catch((enqueueErr) => {
        log.error("auto_pipeline_enqueue_failed", {
          jobId: job.id,
          error: enqueueErr instanceof Error ? enqueueErr : new Error(String(enqueueErr)),
        });
      });
    })
    .catch((err) => {
      taskLog.fail(err);
      // Only overwrite title when analysis itself fails
      prisma.job
        .update({
          where: { id: job.id },
          data: { title: "Analysis Failed — Click to Retry" },
        })
        .catch((dbErr) => log.error("analysis_fallback_update_failed", { jobId: job.id, error: dbErr instanceof Error ? dbErr : new Error(String(dbErr)) }));
    });

  // Return immediately with the placeholder job
  return NextResponse.json({
    ...job,
    captureTitle: typeof titleHint === "string" && titleHint.trim() ? titleHint.trim() : null,
    resumes: [],
    analysisStatus: "pending",
  });
});
